import 'package:flutter/cupertino.dart';

class AlertData {
  static const List<Map<String, String>> alerts = [
    {
      'title': '高温告警',
      'time': '2025-06-04 10:23',
      'desc': '设备A温度超过阈值',
      'handler': '张三',
      'handlerTime': '2025-06-04 10:25',
      'status': '处理中',
      'priority': '高',
      'reply': '已派人检查',
    },
    {
      'title': '断电告警',
      'time': '2025-06-04 09:58',
      'desc': '设备B电源中断',
      'handler': '李四',
      'handlerTime': '2025-06-04 10:00',
      'status': '已处理',
      'priority': '中',
      'reply': '电源已恢复',
    },
    {
      'title': '网络异常',
      'time': '2025-06-03 22:15',
      'desc': '设备C网络连接丢失',
      'handler': '王五',
      'handlerTime': '2025-06-03 22:20',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    {
      'title': '烟雾报警',
      'time': '2025-06-03 21:10',
      'desc': '设备D检测到烟雾',
      'handler': '赵六',
      'handlerTime': '2025-06-03 21:12',
      'status': '处理中',
      'priority': '高',
      'reply': '已通知安保',
    },
    {
      'title': '门禁异常',
      'time': '2025-06-03 20:45',
      'desc': '设备E门禁未关闭',
      'handler': '钱七',
      'handlerTime': '2025-06-03 20:50',
      'status': '已处理',
      'priority': '低',
      'reply': '门禁已关闭',
    },
    {
      'title': '湿度过高',
      'time': '2025-06-03 19:30',
      'desc': '设备F湿度超过阈值',
      'handler': '孙八',
      'handlerTime': '2025-06-03 19:35',
      'status': '处理中',
      'priority': '中',
      'reply': '已调整湿度',
    },
    {
      'title': '电池低电量',
      'time': '2025-06-03 18:20',
      'desc': '设备G电池电量低',
      'handler': '周九',
      'handlerTime': '2025-06-03 18:25',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    {
      'title': '设备离线',
      'time': '2025-06-03 17:05',
      'desc': '设备H已离线',
      'handler': '吴十',
      'handlerTime': '2025-06-03 17:10',
      'status': '已处理',
      'priority': '中',
      'reply': '设备已上线',
    },
    {
      'title': '异常重启',
      'time': '2025-06-03 16:50',
      'desc': '设备I发生异常重启',
      'handler': '郑十一',
      'handlerTime': '2025-06-03 16:55',
      'status': '处理中',
      'priority': '高',
      'reply': '已检查设备',
    },
    {
      'title': '温度恢复',
      'time': '2025-06-03 16:30',
      'desc': '设备A温度恢复正常',
      'handler': '张三',
      'handlerTime': '2025-06-03 16:32',
      'status': '已处理',
      'priority': '低',
      'reply': '温度正常',
    },
  ];

  static final Map<String, IconData> alertIcons = {
    '高温告警': CupertinoIcons.thermometer,
    '断电告警': CupertinoIcons.bolt,
    '网络异常': CupertinoIcons.wifi_exclamationmark,
    '烟雾报警': CupertinoIcons.flame,
    '门禁异常': CupertinoIcons.lock_slash,
    '湿度过高': CupertinoIcons.drop,
    '电池低电量': CupertinoIcons.battery_25,
    '设备离线': CupertinoIcons.xmark_circle,
    '异常重启': CupertinoIcons.refresh,
    '温度恢复': CupertinoIcons.thermometer,
    '电源恢复': CupertinoIcons.bolt_horizontal,
    '网络恢复': CupertinoIcons.wifi,
    '烟雾解除': CupertinoIcons.flame,
    '门禁恢复': CupertinoIcons.lock_open,
    '湿度恢复': CupertinoIcons.drop,
    '电池更换': CupertinoIcons.battery_100,
    '设备上线': CupertinoIcons.check_mark_circled,
    '重启成功': CupertinoIcons.refresh_circled,
  };
}
