import 'package:flutter/cupertino.dart';

class AlertData {
  static const List<Map<String, String>> alerts = [
    // 1
    {
      'title': '高温告警',
      'time': '2025-06-01 10:23',
      'desc': '设备A温度超过阈值',
      'handler': '张三',
      'handlerTime': '2025-06-01 10:25',
      'status': '处理中',
      'priority': '高',
      'reply': '已派人检查',
    },
    // 2
    {
      'title': '断电告警',
      'time': '2025-06-02 09:58',
      'desc': '设备B电源中断',
      'handler': '李四',
      'handlerTime': '2025-06-02 10:00',
      'status': '已处理',
      'priority': '中',
      'reply': '电源已恢复',
    },
    // 3
    {
      'title': '网络异常',
      'time': '2025-06-03 22:15',
      'desc': '设备C网络连接丢失',
      'handler': '王五',
      'handlerTime': '2025-06-03 22:20',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    // 4
    {
      'title': '烟雾报警',
      'time': '2025-06-04 21:10',
      'desc': '设备D检测到烟雾',
      'handler': '赵六',
      'handlerTime': '2025-06-04 21:12',
      'status': '处理中',
      'priority': '高',
      'reply': '已通知安保',
    },
    // 5
    {
      'title': '门禁异常',
      'time': '2025-06-05 20:45',
      'desc': '设备E门禁未关闭',
      'handler': '钱七',
      'handlerTime': '2025-06-05 20:50',
      'status': '已处理',
      'priority': '低',
      'reply': '门禁已关闭',
    },
    // 6
    {
      'title': '湿度过高',
      'time': '2025-06-06 19:30',
      'desc': '设备F湿度超过阈值',
      'handler': '孙八',
      'handlerTime': '2025-06-06 19:35',
      'status': '处理中',
      'priority': '中',
      'reply': '已调整湿度',
    },
    // 7
    {
      'title': '电池低电量',
      'time': '2025-06-07 18:20',
      'desc': '设备G电池电量低',
      'handler': '周九',
      'handlerTime': '2025-06-07 18:25',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    // 8
    {
      'title': '设备离线',
      'time': '2025-06-08 17:05',
      'desc': '设备H已离线',
      'handler': '吴十',
      'handlerTime': '2025-06-08 17:10',
      'status': '已处理',
      'priority': '中',
      'reply': '设备已上线',
    },
    // 9
    {
      'title': '异常重启',
      'time': '2025-06-09 16:50',
      'desc': '设备I发生异常重启',
      'handler': '郑十一',
      'handlerTime': '2025-06-09 16:55',
      'status': '处理中',
      'priority': '高',
      'reply': '已检查设备',
    },
    // 10
    {
      'title': '温度恢复',
      'time': '2025-06-10 16:30',
      'desc': '设备A温度恢复正常',
      'handler': '张三',
      'handlerTime': '2025-06-10 16:32',
      'status': '已处理',
      'priority': '低',
      'reply': '温度正常',
    },
    // 11
    {
      'title': '设备维护',
      'time': '2025-06-11 16:10',
      'desc': '设备J例行维护提醒',
      'handler': '钱十二',
      'handlerTime': '2025-06-11 16:15',
      'status': '已处理',
      'priority': '低',
      'reply': '维护完成',
    },
    // 12
    {
      'title': '高温告警',
      'time': '2025-06-12 15:55',
      'desc': '设备K温度超过阈值',
      'handler': '孙十三',
      'handlerTime': '2025-06-12 16:00',
      'status': '处理中',
      'priority': '高',
      'reply': '已派人检查',
    },
    // 13
    {
      'title': '断电告警',
      'time': '2025-06-13 15:40',
      'desc': '设备L电源中断',
      'handler': '周十四',
      'handlerTime': '2025-06-13 15:45',
      'status': '待处理',
      'priority': '中',
      'reply': '',
    },
    // 14
    {
      'title': '网络异常',
      'time': '2025-06-14 15:25',
      'desc': '设备M网络连接丢失',
      'handler': '吴十五',
      'handlerTime': '2025-06-14 15:30',
      'status': '处理中',
      'priority': '高',
      'reply': '已通知网络组',
    },
    // 15
    {
      'title': '烟雾报警',
      'time': '2025-06-15 15:10',
      'desc': '设备N检测到烟雾',
      'handler': '郑十六',
      'handlerTime': '2025-06-15 15:12',
      'status': '已处理',
      'priority': '高',
      'reply': '已通知安保',
    },
    // 16
    {
      'title': '门禁异常',
      'time': '2025-06-16 14:55',
      'desc': '设备O门禁未关闭',
      'handler': '王十七',
      'handlerTime': '2025-06-16 15:00',
      'status': '处理中',
      'priority': '低',
      'reply': '',
    },
    // 17
    {
      'title': '湿度过高',
      'time': '2025-06-17 14:40',
      'desc': '设备P湿度超过阈值',
      'handler': '李十八',
      'handlerTime': '2025-06-17 14:45',
      'status': '待处理',
      'priority': '中',
      'reply': '',
    },
    // 18
    {
      'title': '电池低电量',
      'time': '2025-06-18 14:25',
      'desc': '设备Q电池电量低',
      'handler': '赵十九',
      'handlerTime': '2025-06-18 14:30',
      'status': '处理中',
      'priority': '高',
      'reply': '已更换电池',
    },
    // 19
    {
      'title': '设备离线',
      'time': '2025-06-19 14:10',
      'desc': '设备R已离线',
      'handler': '钱二十',
      'handlerTime': '2025-06-19 14:15',
      'status': '已处理',
      'priority': '中',
      'reply': '设备已上线',
    },
    // 20
    {
      'title': '异常重启',
      'time': '2025-06-20 13:55',
      'desc': '设备S发生异常重启',
      'handler': '孙二一',
      'handlerTime': '2025-06-20 14:00',
      'status': '处理中',
      'priority': '高',
      'reply': '已检查设备',
    },
    // 21
    {
      'title': '温度恢复',
      'time': '2025-06-21 13:40',
      'desc': '设备K温度恢复正常',
      'handler': '孙十三',
      'handlerTime': '2025-06-21 13:42',
      'status': '已处理',
      'priority': '低',
      'reply': '温度正常',
    },
    // 22
    {
      'title': '高温告警',
      'time': '2025-06-22 13:25',
      'desc': '设备S温度超过阈值',
      'handler': '郑十六',
      'handlerTime': '2025-06-22 13:30',
      'status': '处理中',
      'priority': '高',
      'reply': '已派人检查',
    },
    // 23
    {
      'title': '断电告警',
      'time': '2025-06-23 13:10',
      'desc': '设备T电源中断',
      'handler': '王二二',
      'handlerTime': '2025-06-23 13:15',
      'status': '待处理',
      'priority': '中',
      'reply': '',
    },
    // 24
    {
      'title': '网络异常',
      'time': '2025-06-24 12:55',
      'desc': '设备U网络连接丢失',
      'handler': '李二三',
      'handlerTime': '2025-06-24 13:00',
      'status': '处理中',
      'priority': '高',
      'reply': '已通知网络组',
    },
    // 25
    {
      'title': '烟雾报警',
      'time': '2025-06-25 12:40',
      'desc': '设备V检测到烟雾',
      'handler': '赵二四',
      'handlerTime': '2025-06-25 12:42',
      'status': '已处理',
      'priority': '高',
      'reply': '已通知安保',
    },
    // 26
    {
      'title': '门禁异常',
      'time': '2025-06-26 12:25',
      'desc': '设备W门禁未关闭',
      'handler': '钱二五',
      'handlerTime': '2025-06-26 12:30',
      'status': '处理中',
      'priority': '低',
      'reply': '',
    },
    // 27
    {
      'title': '湿度过高',
      'time': '2025-06-27 12:10',
      'desc': '设备X湿度超过阈值',
      'handler': '孙二六',
      'handlerTime': '2025-06-27 12:15',
      'status': '待处理',
      'priority': '中',
      'reply': '',
    },
    // 28
    {
      'title': '电池低电量',
      'time': '2025-06-28 11:55',
      'desc': '设备Y电池电量低',
      'handler': '周二七',
      'handlerTime': '2025-06-28 12:00',
      'status': '处理中',
      'priority': '高',
      'reply': '已更换电池',
    },
    // 29
    {
      'title': '设备离线',
      'time': '2025-06-29 11:40',
      'desc': '设备Z已离线',
      'handler': '吴二八',
      'handlerTime': '2025-06-29 11:45',
      'status': '已处理',
      'priority': '中',
      'reply': '设备已上线',
    },
    // 30
    {
      'title': '异常重启',
      'time': '2025-06-30 11:25',
      'desc': '设备AA发生异常重启',
      'handler': '郑二九',
      'handlerTime': '2025-06-30 11:30',
      'status': '处理中',
      'priority': '高',
      'reply': '已检查设备',
    },
    // 1
    {
      'title': '高温告警',
      'time': '2025-06-01 10:23',
      'desc': '设备A温度超过阈值',
      'handler': '张三',
      'handlerTime': '2025-06-01 10:25',
      'status': '处理中',
      'priority': '高',
      'reply': '已派人检查',
    },
    // 2
    {
      'title': '断电告警',
      'time': '2025-06-02 09:58',
      'desc': '设备B电源中断',
      'handler': '李四',
      'handlerTime': '2025-06-02 10:00',
      'status': '已处理',
      'priority': '中',
      'reply': '电源已恢复',
    },
    // 3
    {
      'title': '网络异常',
      'time': '2025-06-03 22:15',
      'desc': '设备C网络连接丢失',
      'handler': '王五',
      'handlerTime': '2025-06-03 22:20',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    // 4
    {
      'title': '烟雾报警',
      'time': '2025-06-04 21:10',
      'desc': '设备D检测到烟雾',
      'handler': '赵六',
      'handlerTime': '2025-06-04 21:12',
      'status': '处理中',
      'priority': '高',
      'reply': '已通知安保',
    },
    // 5
    {
      'title': '门禁异常',
      'time': '2025-06-05 20:45',
      'desc': '设备E门禁未关闭',
      'handler': '钱七',
      'handlerTime': '2025-06-05 20:50',
      'status': '已处理',
      'priority': '低',
      'reply': '门禁已关闭',
    },
    // 6
    {
      'title': '湿度过高',
      'time': '2025-06-06 19:30',
      'desc': '设备F湿度超过阈值',
      'handler': '孙八',
      'handlerTime': '2025-06-06 19:35',
      'status': '处理中',
      'priority': '中',
      'reply': '已调整湿度',
    },
    // 7
    {
      'title': '电池低电量',
      'time': '2025-06-07 18:20',
      'desc': '设备G电池电量低',
      'handler': '周九',
      'handlerTime': '2025-06-07 18:25',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    // 8
    {
      'title': '设备离线',
      'time': '2025-06-08 17:05',
      'desc': '设备H已离线',
      'handler': '吴十',
      'handlerTime': '2025-06-08 17:10',
      'status': '已处理',
      'priority': '中',
      'reply': '设备已上线',
    },
    // 9
    {
      'title': '异常重启',
      'time': '2025-06-09 16:50',
      'desc': '设备I发生异常重启',
      'handler': '郑十一',
      'handlerTime': '2025-06-09 16:55',
      'status': '处理中',
      'priority': '高',
      'reply': '已检查设备',
    },
    // 10
    {
      'title': '温度恢复',
      'time': '2025-06-10 16:30',
      'desc': '设备A温度恢复正常',
      'handler': '张三',
      'handlerTime': '2025-06-10 16:32',
      'status': '已处理',
      'priority': '低',
      'reply': '温度正常',
    },
  ];

  static final Map<String, IconData> alertIcons = {
    '高温告警': CupertinoIcons.thermometer,
    '断电告警': CupertinoIcons.bolt,
    '网络异常': CupertinoIcons.wifi_exclamationmark,
    '烟雾报警': CupertinoIcons.flame,
    '门禁异常': CupertinoIcons.lock_slash,
    '湿度过高': CupertinoIcons.drop,
    '电池低电量': CupertinoIcons.battery_25,
    '设备离线': CupertinoIcons.xmark_circle,
    '异常重启': CupertinoIcons.refresh,
    '温度恢复': CupertinoIcons.thermometer,
    '电源恢复': CupertinoIcons.bolt_horizontal,
    '网络恢复': CupertinoIcons.wifi,
    '烟雾解除': CupertinoIcons.flame,
    '门禁恢复': CupertinoIcons.lock_open,
    '湿度恢复': CupertinoIcons.drop,
    '电池更换': CupertinoIcons.battery_100,
    '设备上线': CupertinoIcons.check_mark_circled,
    '重启成功': CupertinoIcons.refresh_circled,
  };
}
