import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class AlertTabPage extends StatelessWidget {
  const AlertTabPage({super.key});

  // 示例告警数据（100条样本）
  final List<Map<String, String>> alerts = const [
    {
      'title': '高温告警',
      'time': '2025-06-04 10:23',
      'desc': '设备A温度超过阈值',
      'handler': '张三',
      'handlerTime': '2025-06-04 10:25',
      'status': '处理中',
      'priority': '高',
      'reply': '已派人检查',
    },
    {
      'title': '断电告警',
      'time': '2025-06-04 09:58',
      'desc': '设备B电源中断',
      'handler': '李四',
      'handlerTime': '2025-06-04 10:00',
      'status': '已处理',
      'priority': '中',
      'reply': '电源已恢复',
    },
    {
      'title': '网络异常',
      'time': '2025-06-03 22:15',
      'desc': '设备C网络连接丢失',
      'handler': '王五',
      'handlerTime': '2025-06-03 22:20',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    {
      'title': '烟雾报警',
      'time': '2025-06-03 21:10',
      'desc': '设备D检测到烟雾',
      'handler': '赵六',
      'handlerTime': '2025-06-03 21:12',
      'status': '处理中',
      'priority': '高',
      'reply': '已通知安保',
    },
    {
      'title': '门禁异常',
      'time': '2025-06-03 20:45',
      'desc': '设备E门禁未关闭',
      'handler': '钱七',
      'handlerTime': '2025-06-03 20:50',
      'status': '已处理',
      'priority': '低',
      'reply': '门禁已关闭',
    },
    {
      'title': '湿度过高',
      'time': '2025-06-03 19:30',
      'desc': '设备F湿度超过阈值',
      'handler': '孙八',
      'handlerTime': '2025-06-03 19:35',
      'status': '处理中',
      'priority': '中',
      'reply': '已调整湿度',
    },
    {
      'title': '电池低电量',
      'time': '2025-06-03 18:20',
      'desc': '设备G电池电量低',
      'handler': '周九',
      'handlerTime': '2025-06-03 18:25',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    {
      'title': '设备离线',
      'time': '2025-06-03 17:05',
      'desc': '设备H已离线',
      'handler': '吴十',
      'handlerTime': '2025-06-03 17:10',
      'status': '已处理',
      'priority': '中',
      'reply': '设备已上线',
    },
    {
      'title': '异常重启',
      'time': '2025-06-03 16:50',
      'desc': '设备I发生异常重启',
      'handler': '郑十一',
      'handlerTime': '2025-06-03 16:55',
      'status': '处理中',
      'priority': '高',
      'reply': '已检查设备',
    },
    {
      'title': '温度恢复',
      'time': '2025-06-03 16:30',
      'desc': '设备A温度恢复正常',
      'handler': '张三',
      'handlerTime': '2025-06-03 16:32',
      'status': '已处理',
      'priority': '低',
      'reply': '温度正常',
    },
    {
      'title': '电源恢复',
      'time': '2025-06-03 16:10',
      'desc': '设备B电源已恢复',
      'handler': '李四',
      'handlerTime': '2025-06-03 16:12',
      'status': '已处理',
      'priority': '中',
      'reply': '电源已恢复',
    },
    {
      'title': '网络恢复',
      'time': '2025-06-03 15:55',
      'desc': '设备C网络已恢复',
      'handler': '王五',
      'handlerTime': '2025-06-03 15:57',
      'status': '已处理',
      'priority': '低',
      'reply': '网络正常',
    },
    {
      'title': '烟雾解除',
      'time': '2025-06-03 15:40',
      'desc': '设备D烟雾警报解除',
      'handler': '赵六',
      'handlerTime': '2025-06-03 15:42',
      'status': '已处理',
      'priority': '低',
      'reply': '烟雾已解除',
    },
    {
      'title': '门禁恢复',
      'time': '2025-06-03 15:25',
      'desc': '设备E门禁已关闭',
      'handler': '钱七',
      'handlerTime': '2025-06-03 15:27',
      'status': '已处理',
      'priority': '低',
      'reply': '门禁正常',
    },
    {
      'title': '湿度恢复',
      'time': '2025-06-03 15:10',
      'desc': '设备F湿度恢复正常',
      'handler': '孙八',
      'handlerTime': '2025-06-03 15:12',
      'status': '已处理',
      'priority': '低',
      'reply': '湿度正常',
    },
    {
      'title': '电池更换',
      'time': '2025-06-03 14:55',
      'desc': '设备G电池已更换',
      'handler': '周九',
      'handlerTime': '2025-06-03 14:57',
      'status': '已处理',
      'priority': '中',
      'reply': '电池已更换',
    },
    {
      'title': '设备上线',
      'time': '2025-06-03 14:40',
      'desc': '设备H已上线',
      'handler': '吴十',
      'handlerTime': '2025-06-03 14:42',
      'status': '已处理',
      'priority': '低',
      'reply': '设备正常',
    },
    {
      'title': '重启成功',
      'time': '2025-06-03 14:25',
      'desc': '设备I重启成功',
      'handler': '郑十一',
      'handlerTime': '2025-06-03 14:27',
      'status': '已处理',
      'priority': '低',
      'reply': '重启正常',
    },
    {
      'title': '高温告警',
      'time': '2025-06-03 14:10',
      'desc': '设备J温度超过阈值',
      'handler': '张三',
      'handlerTime': '2025-06-03 14:12',
      'status': '处理中',
      'priority': '高',
      'reply': '已派人检查',
    },
    {
      'title': '断电告警',
      'time': '2025-06-03 13:55',
      'desc': '设备K电源中断',
      'handler': '李四',
      'handlerTime': '2025-06-03 13:57',
      'status': '已处理',
      'priority': '中',
      'reply': '电源已恢复',
    },
    {
      'title': '网络异常',
      'time': '2025-06-03 13:40',
      'desc': '设备L网络连接丢失',
      'handler': '王五',
      'handlerTime': '2025-06-03 13:45',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    {
      'title': '烟雾报警',
      'time': '2025-06-03 13:25',
      'desc': '设备M检测到烟雾',
      'handler': '赵六',
      'handlerTime': '2025-06-03 13:27',
      'status': '处理中',
      'priority': '高',
      'reply': '已通知安保',
    },
    {
      'title': '门禁异常',
      'time': '2025-06-03 13:10',
      'desc': '设备N门禁未关闭',
      'handler': '钱七',
      'handlerTime': '2025-06-03 13:12',
      'status': '已处理',
      'priority': '低',
      'reply': '门禁已关闭',
    },
    {
      'title': '湿度过高',
      'time': '2025-06-03 12:55',
      'desc': '设备O湿度超过阈值',
      'handler': '孙八',
      'handlerTime': '2025-06-03 12:58',
      'status': '处理中',
      'priority': '中',
      'reply': '已调整湿度',
    },
    {
      'title': '电池低电量',
      'time': '2025-06-03 12:40',
      'desc': '设备P电池电量低',
      'handler': '周九',
      'handlerTime': '2025-06-03 12:45',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    {
      'title': '设备离线',
      'time': '2025-06-03 12:25',
      'desc': '设备Q已离线',
      'handler': '吴十',
      'handlerTime': '2025-06-03 12:30',
      'status': '已处理',
      'priority': '中',
      'reply': '设备已上线',
    },
    {
      'title': '异常重启',
      'time': '2025-06-03 12:10',
      'desc': '设备R发生异常重启',
      'handler': '郑十一',
      'handlerTime': '2025-06-03 12:15',
      'status': '处理中',
      'priority': '高',
      'reply': '已检查设备',
    },
    {
      'title': '温度恢复',
      'time': '2025-06-03 11:55',
      'desc': '设备J温度恢复正常',
      'handler': '张三',
      'handlerTime': '2025-06-03 11:57',
      'status': '已处理',
      'priority': '低',
      'reply': '温度正常',
    },
    {
      'title': '电源恢复',
      'time': '2025-06-03 11:40',
      'desc': '设备K电源已恢复',
      'handler': '李四',
      'handlerTime': '2025-06-03 11:42',
      'status': '已处理',
      'priority': '中',
      'reply': '电源已恢复',
    },
    {
      'title': '网络恢复',
      'time': '2025-06-03 11:25',
      'desc': '设备L网络已恢复',
      'handler': '王五',
      'handlerTime': '2025-06-03 11:27',
      'status': '已处理',
      'priority': '低',
      'reply': '网络正常',
    },
    {
      'title': '烟雾解除',
      'time': '2025-06-03 11:10',
      'desc': '设备M烟雾警报解除',
      'handler': '赵六',
      'handlerTime': '2025-06-03 11:12',
      'status': '已处理',
      'priority': '低',
      'reply': '烟雾已解除',
    },
    {
      'title': '门禁恢复',
      'time': '2025-06-03 10:55',
      'desc': '设备N门禁已关闭',
      'handler': '钱七',
      'handlerTime': '2025-06-03 10:57',
      'status': '已处理',
      'priority': '低',
      'reply': '门禁正常',
    },
    {
      'title': '湿度恢复',
      'time': '2025-06-03 10:40',
      'desc': '设备O湿度恢复正常',
      'handler': '孙八',
      'handlerTime': '2025-06-03 10:42',
      'status': '已处理',
      'priority': '低',
      'reply': '湿度正常',
    },
    {
      'title': '电池更换',
      'time': '2025-06-03 10:25',
      'desc': '设备P电池已更换',
      'handler': '周九',
      'handlerTime': '2025-06-03 10:27',
      'status': '已处理',
      'priority': '中',
      'reply': '电池已更换',
    },
    {
      'title': '设备上线',
      'time': '2025-06-03 10:10',
      'desc': '设备Q已上线',
      'handler': '吴十',
      'handlerTime': '2025-06-03 10:12',
      'status': '已处理',
      'priority': '低',
      'reply': '设备正常',
    },
    {
      'title': '重启成功',
      'time': '2025-06-03 09:55',
      'desc': '设备R重启成功',
      'handler': '郑十一',
      'handlerTime': '2025-06-03 09:57',
      'status': '已处理',
      'priority': '低',
      'reply': '重启正常',
    },
    {
      'title': '高温告警',
      'time': '2025-06-03 09:40',
      'desc': '设备S温度超过阈值',
      'handler': '张三',
      'handlerTime': '2025-06-03 09:42',
      'status': '处理中',
      'priority': '高',
      'reply': '已派人检查',
    },
    {
      'title': '断电告警',
      'time': '2025-06-03 09:25',
      'desc': '设备T电源中断',
      'handler': '李四',
      'handlerTime': '2025-06-03 09:27',
      'status': '已处理',
      'priority': '中',
      'reply': '电源已恢复',
    },
    {
      'title': '网络异常',
      'time': '2025-06-03 09:10',
      'desc': '设备U网络连接丢失',
      'handler': '王五',
      'handlerTime': '2025-06-03 09:15',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    {
      'title': '烟雾报警',
      'time': '2025-06-03 08:55',
      'desc': '设备V检测到烟雾',
      'handler': '赵六',
      'handlerTime': '2025-06-03 08:57',
      'status': '处理中',
      'priority': '高',
      'reply': '已通知安保',
    },
    {
      'title': '门禁异常',
      'time': '2025-06-03 08:40',
      'desc': '设备W门禁未关闭',
      'handler': '钱七',
      'handlerTime': '2025-06-03 08:42',
      'status': '已处理',
      'priority': '低',
      'reply': '门禁已关闭',
    },
    {
      'title': '湿度过高',
      'time': '2025-06-03 08:25',
      'desc': '设备X湿度超过阈值',
      'handler': '孙八',
      'handlerTime': '2025-06-03 08:28',
      'status': '处理中',
      'priority': '中',
      'reply': '已调整湿度',
    },
    {
      'title': '电池低电量',
      'time': '2025-06-03 08:10',
      'desc': '设备Y电池电量低',
      'handler': '周九',
      'handlerTime': '2025-06-03 08:15',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    {
      'title': '设备离线',
      'time': '2025-06-03 07:55',
      'desc': '设备Z已离线',
      'handler': '吴十',
      'handlerTime': '2025-06-03 08:00',
      'status': '已处理',
      'priority': '中',
      'reply': '设备已上线',
    },
    {
      'title': '异常重启',
      'time': '2025-06-03 07:40',
      'desc': '设备AA发生异常重启',
      'handler': '郑十一',
      'handlerTime': '2025-06-03 07:45',
      'status': '处理中',
      'priority': '高',
      'reply': '已检查设备',
    },
    {
      'title': '温度恢复',
      'time': '2025-06-03 07:25',
      'desc': '设备S温度恢复正常',
      'handler': '张三',
      'handlerTime': '2025-06-03 07:27',
      'status': '已处理',
      'priority': '低',
      'reply': '温度正常',
    },
    {
      'title': '电源恢复',
      'time': '2025-06-03 07:10',
      'desc': '设备T电源已恢复',
      'handler': '李四',
      'handlerTime': '2025-06-03 07:12',
      'status': '已处理',
      'priority': '中',
      'reply': '电源已恢复',
    },
    {
      'title': '网络恢复',
      'time': '2025-06-03 06:55',
      'desc': '设备U网络已恢复',
      'handler': '王五',
      'handlerTime': '2025-06-03 06:57',
      'status': '已处理',
      'priority': '低',
      'reply': '网络正常',
    },
    {
      'title': '烟雾解除',
      'time': '2025-06-03 06:40',
      'desc': '设备V烟雾警报解除',
      'handler': '赵六',
      'handlerTime': '2025-06-03 06:42',
      'status': '已处理',
      'priority': '低',
      'reply': '烟雾已解除',
    },
    {
      'title': '门禁恢复',
      'time': '2025-06-03 06:25',
      'desc': '设备W门禁已关闭',
      'handler': '钱七',
      'handlerTime': '2025-06-03 06:27',
      'status': '已处理',
      'priority': '低',
      'reply': '门禁正常',
    },
    {
      'title': '湿度恢复',
      'time': '2025-06-03 06:10',
      'desc': '设备X湿度恢复正常',
      'handler': '孙八',
      'handlerTime': '2025-06-03 06:12',
      'status': '已处理',
      'priority': '低',
      'reply': '湿度正常',
    },
    {
      'title': '电池更换',
      'time': '2025-06-03 05:55',
      'desc': '设备Y电池已更换',
      'handler': '周九',
      'handlerTime': '2025-06-03 05:57',
      'status': '已处理',
      'priority': '中',
      'reply': '电池已更换',
    },
    {
      'title': '设备上线',
      'time': '2025-06-03 05:40',
      'desc': '设备Z已上线',
      'handler': '吴十',
      'handlerTime': '2025-06-03 05:42',
      'status': '已处理',
      'priority': '低',
      'reply': '设备正常',
    },
    {
      'title': '重启成功',
      'time': '2025-06-03 05:25',
      'desc': '设备AA重启成功',
      'handler': '郑十一',
      'handlerTime': '2025-06-03 05:27',
      'status': '已处理',
      'priority': '低',
      'reply': '重启正常',
    },
    {
      'title': '高温告警',
      'time': '2025-06-03 05:10',
      'desc': '设备AB温度超过阈值',
      'handler': '张三',
      'handlerTime': '2025-06-03 05:12',
      'status': '处理中',
      'priority': '高',
      'reply': '已派人检查',
    },
    {
      'title': '断电告警',
      'time': '2025-06-03 04:55',
      'desc': '设备AC电源中断',
      'handler': '李四',
      'handlerTime': '2025-06-03 04:57',
      'status': '已处理',
      'priority': '中',
      'reply': '电源已恢复',
    },
    {
      'title': '网络异常',
      'time': '2025-06-03 04:40',
      'desc': '设备AD网络连接丢失',
      'handler': '王五',
      'handlerTime': '2025-06-03 04:45',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    {
      'title': '烟雾报警',
      'time': '2025-06-03 04:25',
      'desc': '设备AE检测到烟雾',
      'handler': '赵六',
      'handlerTime': '2025-06-03 04:27',
      'status': '处理中',
      'priority': '高',
      'reply': '已通知安保',
    },
    {
      'title': '门禁异常',
      'time': '2025-06-03 04:10',
      'desc': '设备AF门禁未关闭',
      'handler': '钱七',
      'handlerTime': '2025-06-03 04:12',
      'status': '已处理',
      'priority': '低',
      'reply': '门禁已关闭',
    },
    {
      'title': '湿度过高',
      'time': '2025-06-03 03:55',
      'desc': '设备AG湿度超过阈值',
      'handler': '孙八',
      'handlerTime': '2025-06-03 03:58',
      'status': '处理中',
      'priority': '中',
      'reply': '已调整湿度',
    },
    {
      'title': '电池低电量',
      'time': '2025-06-03 03:40',
      'desc': '设备AH电池电量低',
      'handler': '周九',
      'handlerTime': '2025-06-03 03:45',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    {
      'title': '设备离线',
      'time': '2025-06-03 03:25',
      'desc': '设备AI已离线',
      'handler': '吴十',
      'handlerTime': '2025-06-03 03:30',
      'status': '已处理',
      'priority': '中',
      'reply': '设备已上线',
    },
    {
      'title': '异常重启',
      'time': '2025-06-03 03:10',
      'desc': '设备AJ发生异常重启',
      'handler': '郑十一',
      'handlerTime': '2025-06-03 03:15',
      'status': '处理中',
      'priority': '高',
      'reply': '已检查设备',
    },
    {
      'title': '温度恢复',
      'time': '2025-06-03 02:55',
      'desc': '设备AB温度恢复正常',
      'handler': '张三',
      'handlerTime': '2025-06-03 02:57',
      'status': '已处理',
      'priority': '低',
      'reply': '温度正常',
    },
    {
      'title': '电源恢复',
      'time': '2025-06-03 02:40',
      'desc': '设备AC电源已恢复',
      'handler': '李四',
      'handlerTime': '2025-06-03 02:42',
      'status': '已处理',
      'priority': '中',
      'reply': '电源已恢复',
    },
    {
      'title': '网络恢复',
      'time': '2025-06-03 02:25',
      'desc': '设备AD网络已恢复',
      'handler': '王五',
      'handlerTime': '2025-06-03 02:27',
      'status': '已处理',
      'priority': '低',
      'reply': '网络正常',
    },
    {
      'title': '烟雾解除',
      'time': '2025-06-03 02:10',
      'desc': '设备AE烟雾警报解除',
      'handler': '赵六',
      'handlerTime': '2025-06-03 02:12',
      'status': '已处理',
      'priority': '低',
      'reply': '烟雾已解除',
    },
    {
      'title': '门禁恢复',
      'time': '2025-06-03 01:55',
      'desc': '设备AF门禁已关闭',
      'handler': '钱七',
      'handlerTime': '2025-06-03 01:57',
      'status': '已处理',
      'priority': '低',
      'reply': '门禁正常',
    },
    {
      'title': '湿度恢复',
      'time': '2025-06-03 01:40',
      'desc': '设备AG湿度恢复正常',
      'handler': '孙八',
      'handlerTime': '2025-06-03 01:42',
      'status': '已处理',
      'priority': '低',
      'reply': '湿度正常',
    },
    {
      'title': '电池更换',
      'time': '2025-06-03 01:25',
      'desc': '设备AH电池已更换',
      'handler': '周九',
      'handlerTime': '2025-06-03 01:27',
      'status': '已处理',
      'priority': '中',
      'reply': '电池已更换',
    },
    {
      'title': '设备上线',
      'time': '2025-06-03 01:10',
      'desc': '设备AI已上线',
      'handler': '吴十',
      'handlerTime': '2025-06-03 01:12',
      'status': '已处理',
      'priority': '低',
      'reply': '设备正常',
    },
    {
      'title': '重启成功',
      'time': '2025-06-02 23:55',
      'desc': '设备AJ重启成功',
      'handler': '郑十一',
      'handlerTime': '2025-06-02 23:57',
      'status': '已处理',
      'priority': '低',
      'reply': '重启正常',
    },
    {
      'title': '高温告警',
      'time': '2025-06-02 23:40',
      'desc': '设备AK温度超过阈值',
      'handler': '张三',
      'handlerTime': '2025-06-02 23:42',
      'status': '处理中',
      'priority': '高',
      'reply': '已派人检查',
    },
    {
      'title': '断电告警',
      'time': '2025-06-02 23:25',
      'desc': '设备AL电源中断',
      'handler': '李四',
      'handlerTime': '2025-06-02 23:27',
      'status': '已处理',
      'priority': '中',
      'reply': '电源已恢复',
    },
    {
      'title': '网络异常',
      'time': '2025-06-02 23:10',
      'desc': '设备AM网络连接丢失',
      'handler': '王五',
      'handlerTime': '2025-06-02 23:15',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    {
      'title': '烟雾报警',
      'time': '2025-06-02 22:55',
      'desc': '设备AN检测到烟雾',
      'handler': '赵六',
      'handlerTime': '2025-06-02 22:57',
      'status': '处理中',
      'priority': '高',
      'reply': '已通知安保',
    },
    {
      'title': '门禁异常',
      'time': '2025-06-02 22:40',
      'desc': '设备AO门禁未关闭',
      'handler': '钱七',
      'handlerTime': '2025-06-02 22:42',
      'status': '已处理',
      'priority': '低',
      'reply': '门禁已关闭',
    },
    {
      'title': '湿度过高',
      'time': '2025-06-02 22:25',
      'desc': '设备AP湿度超过阈值',
      'handler': '孙八',
      'handlerTime': '2025-06-02 22:28',
      'status': '处理中',
      'priority': '中',
      'reply': '已调整湿度',
    },
    {
      'title': '电池低电量',
      'time': '2025-06-02 22:10',
      'desc': '设备AQ电池电量低',
      'handler': '周九',
      'handlerTime': '2025-06-02 22:15',
      'status': '待处理',
      'priority': '高',
      'reply': '',
    },
    {
      'title': '设备离线',
      'time': '2025-06-02 21:55',
      'desc': '设备AR已离线',
      'handler': '吴十',
      'handlerTime': '2025-06-02 22:00',
      'status': '已处理',
      'priority': '中',
      'reply': '设备已上线',
    },
    {
      'title': '异常重启',
      'time': '2025-06-02 21:40',
      'desc': '设备AS发生异常重启',
      'handler': '郑十一',
      'handlerTime': '2025-06-02 21:45',
      'status': '处理中',
      'priority': '高',
      'reply': '已检查设备',
    },
    {
      'title': '温度恢复',
      'time': '2025-06-02 21:25',
      'desc': '设备AK温度恢复正常',
      'handler': '张三',
      'handlerTime': '2025-06-02 21:27',
      'status': '已处理',
      'priority': '低',
      'reply': '温度正常',
    },
    {
      'title': '电源恢复',
      'time': '2025-06-02 21:10',
      'desc': '设备AL电源已恢复',
      'handler': '李四',
      'handlerTime': '2025-06-02 21:12',
      'status': '已处理',
      'priority': '中',
      'reply': '电源已恢复',
    },
    {
      'title': '网络恢复',
      'time': '2025-06-02 20:55',
      'desc': '设备AM网络已恢复',
      'handler': '王五',
      'handlerTime': '2025-06-02 20:57',
      'status': '已处理',
      'priority': '低',
      'reply': '网络正常',
    },
    {
      'title': '烟雾解除',
      'time': '2025-06-02 20:40',
      'desc': '设备AN烟雾警报解除',
      'handler': '赵六',
      'handlerTime': '2025-06-02 20:42',
      'status': '已处理',
      'priority': '低',
      'reply': '烟雾已解除',
    },
    {
      'title': '门禁恢复',
      'time': '2025-06-02 20:25',
      'desc': '设备AO门禁已关闭',
      'handler': '钱七',
      'handlerTime': '2025-06-02 20:27',
      'status': '已处理',
      'priority': '低',
      'reply': '门禁正常',
    },
    {
      'title': '湿度恢复',
      'time': '2025-06-02 20:10',
      'desc': '设备AP湿度恢复正常',
      'handler': '孙八',
      'handlerTime': '2025-06-02 20:12',
      'status': '已处理',
      'priority': '低',
      'reply': '湿度正常',
    },
    {
      'title': '电池更换',
      'time': '2025-06-02 19:55',
      'desc': '设备AQ电池已更换',
      'handler': '周九',
      'handlerTime': '2025-06-02 19:57',
      'status': '已处理',
      'priority': '中',
      'reply': '电池已更换',
    },
    {
      'title': '设备上线',
      'time': '2025-06-02 19:40',
      'desc': '设备AR已上线',
      'handler': '吴十',
      'handlerTime': '2025-06-02 19:42',
      'status': '已处理',
      'priority': '低',
      'reply': '设备正常',
    },
    {
      'title': '重启成功',
      'time': '2025-06-02 19:25',
      'desc': '设备AS重启成功',
      'handler': '郑十一',
      'handlerTime': '2025-06-02 19:27',
      'status': '已处理',
      'priority': '低',
      'reply': '重启正常',
    },
  ];

  // 告警类型与对应icon
  static final Map<String, IconData> alertIcons = {
    '高温告警': CupertinoIcons.thermometer,
    '断电告警': CupertinoIcons.bolt,
    '网络异常': CupertinoIcons.wifi_exclamationmark,
    '烟雾报警': CupertinoIcons.flame,
    '门禁异常': CupertinoIcons.lock_slash,
    '湿度过高': CupertinoIcons.drop,
    '电池低电量': CupertinoIcons.battery_25,
    '设备离线': CupertinoIcons.xmark_circle,
    '异常重启': CupertinoIcons.refresh,
    '温度恢复': CupertinoIcons.thermometer,
    '电源恢复': CupertinoIcons.bolt_horizontal,
    '网络恢复': CupertinoIcons.wifi,
    '烟雾解除': CupertinoIcons.flame,
    '门禁恢复': CupertinoIcons.lock_open,
    '湿度恢复': CupertinoIcons.drop,
    '电池更换': CupertinoIcons.battery_100,
    '设备上线': CupertinoIcons.check_mark_circled,
    '重启成功': CupertinoIcons.refresh_circled,
  };

  @override
  Widget build(BuildContext context) {
    return CupertinoScrollbar(
      child: Padding(
        padding: const EdgeInsets.only(top: 8), // 给Scrollbar和内容顶部加间距，避免被遮挡
        child: ListView.separated(
          padding: const EdgeInsets.only(
            top: 32,
            left: 16,
            right: 16,
            bottom: 0,
          ),
          itemCount: alerts.length,
          separatorBuilder:
              (context, index) => Container(
                height: 1,
                color: CupertinoColors.systemGrey5,
                margin: const EdgeInsets.only(top: 12), // 增加与上一笔资料的间距
              ),
          itemBuilder: (context, index) {
            final alert = alerts[index];
            final icon =
                alertIcons[alert['title']] ?? CupertinoIcons.bell_solid;
            return CupertinoListTile(
              leading: Icon(icon, color: CupertinoColors.systemRed, size: 32),
              title: Row(
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          alert['title'] ?? '',
                          style: const TextStyle(fontWeight: FontWeight.bold),
                        ),
                        if ((alert['time'] ?? '').isNotEmpty)
                          Padding(
                            padding: const EdgeInsets.only(top: 2),
                            child: Text(
                              alert['time'] ?? '',
                              style: const TextStyle(
                                fontSize: 13,
                                color: CupertinoColors.systemGrey,
                              ),
                            ),
                          ),
                      ],
                    ),
                  ),
                  Container(
                    constraints: const BoxConstraints(
                      minWidth: 80,
                      maxWidth: 120,
                    ),
                    margin: const EdgeInsets.only(left: 8),
                    padding: const EdgeInsets.symmetric(
                      horizontal: 0,
                      vertical: 0,
                    ),
                    decoration: BoxDecoration(
                      gradient: LinearGradient(
                        colors:
                            alert['priority'] == '高'
                                ? [Color(0xFFFF5E62), Color(0xFFFF9966)]
                                : alert['priority'] == '中'
                                ? [Color(0xFFFFF200), Color(0xFFFFC371)]
                                : [Color(0xFF43E97B), Color(0xFF38F9D7)],
                        begin: Alignment.topLeft,
                        end: Alignment.bottomRight,
                      ),
                      borderRadius: BorderRadius.circular(16),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withOpacity(0.06),
                          blurRadius: 8,
                          offset: Offset(0, 2),
                        ),
                      ],
                    ),
                    child: Center(
                      child: Text(
                        '紧急: ${alert['priority'] ?? ''}',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 15,
                          fontWeight: FontWeight.w900,
                          letterSpacing: 1.2,
                          shadows: [
                            Shadow(
                              color: Colors.black.withOpacity(0.08),
                              blurRadius: 2,
                              offset: Offset(1, 1),
                            ),
                          ],
                        ),
                      ),
                    ),
                    height: 32,
                    width: double.infinity,
                  ),
                ],
              ),
              subtitle: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    alert['desc'] ?? '',
                    style: const TextStyle(fontSize: 15),
                  ),
                  const SizedBox(height: 4),
                  Row(
                    children: [
                      Text(
                        '处理人: ${alert['handler']}',
                        style: const TextStyle(fontSize: 13),
                      ),

                      const SizedBox(width: 12),
                      Text(
                        '处理时间: ${alert['handlerTime'] ?? ''}',
                        style: const TextStyle(
                          fontSize: 13,
                          color: CupertinoColors.systemGrey2,
                        ),
                      ),
                      const SizedBox(width: 12),
                      Text(
                        '状态: ${alert['status'] ?? ''}',
                        style: const TextStyle(fontSize: 13),
                      ),
                      const SizedBox(width: 12),
                      Text(
                        '回复: ${alert['reply'] ?? ''}',
                        style: const TextStyle(
                          fontSize: 13,
                          color: CupertinoColors.activeBlue,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
              trailing: const Icon(
                CupertinoIcons.right_chevron,
                color: CupertinoColors.systemGrey,
              ),
              onTap: () {
                // 可在此处理点击事件
              },
            );
          },
        ),
      ),
    );
  }
}
